import { CadiTestLog } from '@/types';
import { calculateCADI } from './cadiEngine';

const rawSeedLogs = [
  {
    id: 'airlit-log-101',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    locationA: { lat: 26.4499, lng: 80.3319 },
    locationB: { lat: 26.4502, lng: 80.3321 },
    distanceMeters: 42,
    verified: true,
    district: 'Kanpur Industrial Zone, UP',
    phColor: 'red' as const,
    initialTDS: 2,
    finalTDS: 16,
    notes: 'Sample taken near tannery gas exhaust output. Strong acidic color shift on paper.',
  },
  {
    id: 'airlit-log-102',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    locationA: { lat: 28.6139, lng: 77.209 },
    locationB: { lat: 28.6141, lng: 77.2093 },
    distanceMeters: 35,
    verified: true,
    district: 'Central Delhi (Connaught Place), DL',
    phColor: 'red' as const,
    initialTDS: 3,
    finalTDS: 11,
    notes: 'Heavy traffic rush hour bubbling test. Ambient NO2 loading confirmed.',
  },
  {
    id: 'airlit-log-103',
    timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    locationA: { lat: 32.2432, lng: 77.1892 },
    locationB: { lat: 32.2434, lng: 77.1894 },
    distanceMeters: 28,
    verified: true,
    district: 'Solang Valley, Manali, HP',
    phColor: 'yellow' as const,
    initialTDS: 1,
    finalTDS: 3,
    notes: 'High altitude baseline test. Pure pristine mountain air column.',
  },
  {
    id: 'airlit-log-104',
    timestamp: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    locationA: { lat: 12.9716, lng: 77.5946 },
    locationB: { lat: 12.9789, lng: 77.6012 },
    distanceMeters: 1140,
    verified: false,
    district: 'Whitefield Tech Corridor, Bengaluru',
    phColor: 'blue' as const,
    initialTDS: 2,
    finalTDS: 8,
    notes: 'Off-site report submitted 2 hours post-scrubbing. Alkaline NH3 fertilizer emissions suspected.',
  },
  {
    id: 'airlit-log-105',
    timestamp: new Date(Date.now() - 1000 * 60 * 1440).toISOString(),
    locationA: { lat: 19.076, lng: 72.8777 },
    locationB: { lat: 19.0763, lng: 72.878 },
    distanceMeters: 55,
    verified: true,
    district: 'Chembur Port & Refinery, Mumbai, MH',
    phColor: 'red' as const,
    initialTDS: 3,
    finalTDS: 18,
    notes: 'Refinery perimeter test. Acid rain precursor hazard SO2 high saturation.',
  },
  {
    id: 'airlit-log-106',
    timestamp: new Date(Date.now() - 1000 * 60 * 2880).toISOString(),
    locationA: { lat: 22.5726, lng: 88.3639 },
    locationB: { lat: 22.5729, lng: 88.3642 },
    distanceMeters: 48,
    verified: true,
    district: 'Howrah Railway Terminus Area, Kolkata',
    phColor: 'red' as const,
    initialTDS: 4,
    finalTDS: 12,
    notes: 'Heavy diesel exhaust accumulation trap in distilled H2O.',
  },
  {
    id: 'airlit-log-107',
    timestamp: new Date(Date.now() - 1000 * 60 * 4320).toISOString(),
    locationA: { lat: 18.5204, lng: 73.8567 },
    locationB: { lat: 18.5207, lng: 73.857 },
    distanceMeters: 31,
    verified: true,
    district: 'Kothrud Residential Zone, Pune',
    phColor: 'yellow' as const,
    initialTDS: 2,
    finalTDS: 5,
    notes: 'Suburban garden environment. Nominal background TDS shift.',
  },
];

export const initialSeedLogs: CadiTestLog[] = rawSeedLogs.map((item) => {
  const calc = calculateCADI(item.phColor, item.initialTDS, item.finalTDS);
  return {
    ...item,
    tdsDelta: calc.tdsDelta,
    cadiScore: calc.cadiScore,
    hazardLevel: calc.hazardLevel,
    hazardColor: calc.hazardColor,
  };
});
